### PR TITLE
Update to Bevy 0.10

### PR DESCRIPTION
**Pull request by NiklasEi**
Most of the diff is a merge from `main` into `bevy_main`

All the real changes are on a single commit. This is the state that I use to update `bevy_asset_loader`. If you consider merging this, I can spend some more time cleaning up.

### CODE REVIEW

**Comment by inodentry** [comment]
Okay! Great! Thanks for doing this! I like how you made all the things be represented using the new bevy stageless.

Before merging this, I'd like to go back to having the individual bevy crates in dependencies, rather than bevy with no default features. Keeps dependency trees slimmer.

A few questions:

1. Why did you pull out `TrackedProgressSet` out of the enum into a separate struct? I like it ... but I'd like to know your reasoning for it.
2. Could we maybe turn those exclusive systems into regular systems now? If I remember correctly, the only reason we made them exclusive before, was to help simplify the user API/ordering under the old model with stages and labels. Now there is no difference, so I don't see why they need to be exclusive.

**Comment by NiklasEi** [comment]
> Before merging this, I'd like to go back to having the individual bevy crates in dependencies, rather than bevy with no default features. Keeps dependency trees slimmer.

Ah, I hadn't thought about that. My thought was only that this would make patching easier. I'll revert it.

1. The enum is a base set, so we can order it after `CoreSet::StateTransition`. Although I am not 100% sure if it needs to be one? I made it one because otherwise, the systems would be in `CoreSet::Update`, but since then I learned, that one can stop systems from being added to the default base set...
The other state `TrackedProgressSet` is not a base set, because I want the users to be able to choose which base set their systems run in.

2. That makes sense :+1:

**Comment by NiklasEi** [comment]
This now depends on and works with the published `0.10` release

**Comment by jeremy-prater** [comment]
Hello! Just wanted to confirm this did help me get past a compiler issue with `AssetsLoading`

I added this to my Cargo.toml
```
iyes_progress = { version = "0.8", features = [ "assets" ], git = "https://github.com/NiklasEi/iyes_progress", branch = "bevy_main"  }
```
which resolved this compiler error
```
error[E0277]: the trait bound `iyes_progress::prelude::AssetsLoading: bevy::prelude::Resource` is not satisfied                                                                                                                             
   --> tictactoe_3d/client/src/systems/splash.rs:12:18                                                                                                                                                                                      
    |                                                                                                                                                                                                                                       
12  |     mut loading: ResMut<AssetsLoading>,                                                                                                                                                                                               
    |                  ^^^^^^^^^^^^^^^^^^^^^ the trait `bevy::prelude::Resource` is not implemented for `iyes_progress::prelude::AssetsLoading`                                                                                             
    |                                                                                                                                                                                                                                       
    = help: the following other types implement trait `bevy::prelude::Resource`:                                                                                                                                                            
              AccessibilityRequested                                                                                                                                                                                                        
              AppTypeRegistry                                                                                                                                                                                                               
              Assets<T>                                                                                                                                                                                                                     
              AudioOutput<Source>                                                                                                                                                                                                           
              BlitPipeline                                                                                                                                                                                                                  
              ClearColor                                                                                                                                                                                                                    
              CloudClient                                                                                                                                                                                                                   
              ComponentUniforms<C>
            and 102 others
note: required by a bound in `bevy::prelude::ResMut`
```

Thanks! :+1:
